# Generated by Django 4.2.27 on 2025-12-31 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_emails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text="Fichier de l'ordonnance (PDF, photo, scan)", upload_to='prescriptions/')),
                ('original_filename', models.CharField(help_text='Nom original du fichier envoyé', max_length=255)),
                ('mime_type', models.CharField(help_text='Type MIME du fichier', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core_emails.prescription')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionAttachmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('VIEW', 'Consultation'), ('DOWNLOAD', 'Téléchargement')], max_length=20)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='core_attachments.prescriptionattachment')),
            ],
        ),
    ]
