# gmail_manager/gmail_manager/settings.py
"""
Django settings for gmail_manager project.

Generated by 'django-admin startproject' using Django 4.2.27.
"""

from pathlib import Path

# ============================================================
# BASE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SÉCURITÉ
# ============================================================

SECRET_KEY = 'django-insecure-3-$n6&7wzfk!#8&g!9qbwjp+0mt+0=s*5j6whf0b)xp(5!x&05'
DEBUG = True
ALLOWED_HOSTS = []


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps métier
    "core_accounts",
    "core_gmail",
    "core_emails",
    "core_attachments",
    "core_notifications",
    "core_patients",
    "core_people",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URLS / TEMPLATES
# ============================================================

ROOT_URLCONF = 'gmail_manager.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR / "gmail_manager" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'gmail_manager.wsgi.application'


# ============================================================
# BASE DE DONNÉES
# ============================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================================================
# VALIDATION MOT DE PASSE
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================================================
# INTERNATIONALISATION
# ============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Europe/Paris"
USE_I18N = True
USE_TZ = True


# ============================================================
# FICHIERS STATIQUES ✅
# ============================================================

STATIC_URL = "/static/"

# static est ici : /home/ksajed/gmail_project/gmail_manager/static
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"




# ============================================================
# FICHIERS MEDIA
# ============================================================

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# GMAIL / IMAP — PHARMACIE
# ============================================================

GMAIL_IMAP_HOST = "imap.gmail.com"
GMAIL_IMAP_PORT = 993
GMAIL_EMAIL = "khalidsajed19755@gmail.com"
GMAIL_APP_PASSWORD = "scnu pbue vnfy cykv"


# ============================================================
# EMAIL SMTP — ENVOI RÉEL
# ============================================================

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "khalidsajed19755@gmail.com"
EMAIL_HOST_PASSWORD = "scnu pbue vnfy cykv"
DEFAULT_FROM_EMAIL = "Votre Grande Pharmacie de Fives <khalidsajed19755@gmail.com>"


# ============================================================
# AUTHENTIFICATION
# ============================================================

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"
