# Generated by Django 6.0.6 on 2026-07-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_anomalies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='severity',
            field=models.CharField(choices=[('CRITIQUE', 'Critique'), ('ELEVEE', 'Élevée'), ('MOYENNE', 'Moyenne'), ('FAIBLE', 'Faible'), ('INFO', 'Information')], default='FAIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='status',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('EN_ATTENTE', 'En attente'), ('RESOLUE', 'Résolue'), ('IGNOREE', 'Ignorée')], default='NOUVELLE', max_length=20),
        ),
    ]
