# Generated by Django 6.0.6 on 2026-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_anomalies', '0002_alter_anomaly_severity_alter_anomaly_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='autofix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
