# Generated by Django 4.2.27 on 2025-12-31 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre court de la notification', max_length=255)),
                ('message', models.TextField(help_text='Message détaillé')),
                ('is_read', models.BooleanField(default=False, help_text='Notification lue ou non')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_type', models.CharField(blank=True, help_text="Type d'objet lié (ex : Prescription)", max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet lié", null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
