# Generated by Django 4.2.27 on 2026-01-09 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0008_prescriptionrenewalevent'),
        ('core_notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=32)),
                ('purpose', models.CharField(choices=[('STATUS_UPDATE', 'Status update'), ('RENEWAL', 'Renewal'), ('INFO', 'Info')], max_length=30)),
                ('template_key', models.CharField(blank=True, default='', max_length=100)),
                ('rendered_text', models.TextField()),
                ('provider', models.CharField(choices=[('OVH', 'OVH')], default='OVH', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('related_prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core_emails.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='SmsAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('sms_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='core_notifications.smsmessage')),
            ],
        ),
    ]
