# Generated by Django 4.2.27 on 2025-12-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('doctor', 'Médecin'), ('nurse', 'Infirmier'), ('patient', 'Patient'), ('other', 'Autre')], help_text='Rôle organisationnel', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personne',
                'verbose_name_plural': 'Personnes',
            },
        ),
    ]
