# Generated by Django 4.2.27 on 2026-02-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_adminconsole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditevent',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User-Agent (best-effort)'),
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP source (best-effort)', null=True),
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Données structurées (JSON) pour analyses/forensics'),
        ),
    ]
