# Generated by Django 4.2.27 on 2026-02-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_adminconsole', '0002_adminauditevent_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminauditevent',
            options={'ordering': ['-created_at'], 'permissions': [('access_console', "Accéder à l'Admin Console"), ('manage_accounts', 'Gérer les comptes'), ('manage_groups', 'Gérer les groupes et permissions'), ('view_audit', "Voir l'audit"), ('clear_audit', "Purger l'audit")]},
        ),
        migrations.AlterField(
            model_name='adminauditevent',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion admin'), ('EXPORT_CSV', 'Export CSV'), ('ACCOUNT_DISABLE', 'Mise en veille compte'), ('ACCOUNT_ENABLE', 'Réactivation compte'), ('CREATE_NURSE', 'Création infirmier'), ('EDIT_NURSE', 'Édition infirmier'), ('UPDATE_NURSE', 'Mise à jour infirmier'), ('DEACTIVATE_NURSE', 'Désactivation infirmier'), ('ACTIVATE_NURSE', 'Réactivation infirmier')], max_length=64),
        ),
    ]
