# Generated by Django 4.2.27 on 2025-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Nom du patient (optionnel en V1)', max_length=255)),
                ('email', models.EmailField(help_text='Email principal du patient (identité V1)', max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text='Numéro de téléphone (optionnel en V1)', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
