# Generated by Django 4.2.27 on 2025-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(help_text='Email principal du patient (identité V1)', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(blank=True, help_text='Nom du patient (optionnel en V1)', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone (optionnel en V1)', max_length=30),
        ),
    ]
