# Generated by Django 4.2.27 on 2025-12-25 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(help_text='Nom complet du patient', max_length=255)),
                ('patient_birth_date', models.DateField(help_text='Date de naissance du patient')),
                ('prescriber_name', models.CharField(help_text='Nom du médecin prescripteur', max_length=255)),
                ('prescriber_rpps', models.CharField(blank=True, help_text='Numéro RPPS du médecin (si connu)', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Remarques internes du pharmacien')),
                ('status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text="Date de réception de l'ordonnance")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur de la pharmacie', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)')], max_length=20)),
                ('new_status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Motif du changement (ex : rupture de stock)')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core_emails.prescription')),
            ],
        ),
    ]
