# Generated by Django 4.2.27 on 2025-12-31 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text="Date de réception de l'ordonnance")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur de la pharmacie', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text="Patient lié à l'ordonnance (créé automatiquement si absent)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core_patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], max_length=20)),
                ('new_status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, help_text='Motif du changement (ex : rupture de stock)')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core_emails.prescription')),
            ],
        ),
    ]
