# Generated by Django 4.2.27 on 2025-12-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_people', '0001_initial'),
        ('core_patients', '0001_initial'),
        ('core_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='sender_type',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('nurse', 'Infirmier'), ('patient', 'Patient'), ('unknown', 'Inconnu')], default='unknown', help_text="Type d'expéditeur de l'ordonnance (organisationnel)", max_length=20),
        ),
        migrations.CreateModel(
            name='PrescriptionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text="Date d'affectation")),
                ('nurse', models.ForeignKey(blank=True, help_text='Infirmier associé (organisationnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescriptions', to='core_people.person')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient concerné (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescriptions', to='core_patients.patient')),
                ('prescription', models.OneToOneField(help_text='Ordonnance concernée', on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='core_emails.prescription')),
            ],
            options={
                'verbose_name': 'Affectation ordonnance',
                'verbose_name_plural': 'Affectations ordonnances',
            },
        ),
    ]
