# Generated by Django 4.2.27 on 2025-12-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_birth_date',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescriber_name',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescriber_rpps',
        ),
    ]
