# Generated by Django 4.2.27 on 2025-12-26 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_patients', '0001_initial'),
        ('core_emails', '0002_remove_prescription_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, help_text="Patient lié à l'ordonnance (créé automatiquement si absent)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='core_patients.patient'),
        ),
    ]
