# Generated by Django 4.2.27 on 2025-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0002_prescription_sender_type_prescriptionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='type',
            field=models.CharField(choices=[('STANDARD', 'Ordonnance classique'), ('RENOUVELLEMENT', 'Renouvellement'), ('ALD', 'ALD'), ('URGENCE', 'Urgence'), ('SORTIE_HOSPITALISATION', 'Sortie d’hospitalisation'), ('DISPOSITIF_MEDICAL', 'Dispositif médical'), ('SOINS_INFIRMIERS', 'Soins infirmiers'), ('STUPEFIANT', 'Stupéfiants'), ('INCOMPLETE', 'Incomplète'), ('A_VERIFIER', 'À vérifier'), ('PSYCHOTROPE', 'Psychotrope'), ('MEDICAMENT_EXCEPTION', 'Médicament d’exception'), ('HOSPITALIERE', 'Hospitalière'), ('RESTRICTIVE', 'Prescription restreinte'), ('HORS_AMM', 'Hors AMM'), ('PEDIATRIQUE', 'Pédiatrique'), ('PERSONNE_AGEE', 'Personne âgée'), ('EHPAD', 'EHPAD'), ('HAD', 'HAD'), ('SSIAD', 'SSIAD'), ('PANSEMENTS', 'Pansements'), ('OXYGENOTHERAPIE', 'Oxygénothérapie'), ('NUTRITION', 'Nutrition'), ('PERFUSION', 'Perfusion'), ('ORTHOPEDIQUE', 'Orthopédique'), ('VETERINAIRE', 'Vétérinaire'), ('ORDONNANCE_ETRANGERE', 'Ordonnance étrangère'), ('DOM_TOM', 'DOM-TOM'), ('ESSAI_CLINIQUE', 'Essai clinique'), ('IMPORTATION', 'Importation'), ('ILLISIBLE', 'Illisible'), ('DUPLICATA', 'Duplicata'), ('RECTIFICATIVE', 'Rectificative'), ('BLOQUEE_ADMIN', 'Bloquée (administratif)'), ('ARCHIVE_PAPIER', 'Archivée papier'), ('AUTRE', 'Autre')], default='STANDARD', help_text='Type organisationnel de l’ordonnance (non médical)', max_length=40),
        ),
    ]
