# Generated by Django 4.2.27 on 2025-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0003_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], default='RECEIVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionstatushistory',
            name='new_status',
            field=models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prescriptionstatushistory',
            name='old_status',
            field=models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], max_length=20),
        ),
    ]
