# Generated by Django 4.2.27 on 2026-01-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0004_alter_prescription_sender_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='sender_type',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('dentist', 'Chirurgien-dentiste'), ('midwife', 'Sage-femme'), ('nurse', 'Infirmier'), ('physiotherapist', 'Masseur-kinésithérapeute'), ('speech_therapist', 'Orthophoniste'), ('podiatrist', 'Pédicure-podologue'), ('patient', 'Patient'), ('unknown', 'Inconnu')], default='unknown', help_text="Type d'expéditeur de l'ordonnance (organisationnel)", max_length=20),
        ),
    ]
