# Generated by Django 4.2.27 on 2026-01-06 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0005_alter_prescription_sender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='established_at',
            field=models.DateField(blank=True, help_text='Date d’établissement de l’ordonnance (date médecin) — base des calculs de renouvellement', null=True),
        ),
        migrations.CreateModel(
            name='PrescriptionRenewalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_times', models.PositiveSmallIntegerField(default=0)),
                ('period_days', models.PositiveSmallIntegerField(default=30)),
                ('doctor_email', models.EmailField(blank=True, max_length=254)),
                ('doctor_name', models.CharField(blank=True, max_length=120)),
                ('reminder_5_patient_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_5_patient_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3_patient_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3_patient_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_info', to='core_emails.prescription')),
            ],
        ),
    ]
