# Generated by Django 4.2.27 on 2026-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0006_prescription_established_at_prescriptionrenewalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrenewalinfo',
            name='last_renewal_ordered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionrenewalinfo',
            name='renewal_done_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
