# Generated by Django 4.2.27 on 2026-01-08 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_emails', '0007_prescriptionrenewalinfo_last_renewal_ordered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRenewalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_renewal_events', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_events', to='core_emails.prescription')),
            ],
            options={
                'ordering': ['-ordered_at'],
                'unique_together': {('prescription', 'number')},
            },
        ),
    ]
