# Generated by Django 4.2.27 on 2026-01-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_emails', '0008_prescriptionrenewalevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_channel', models.CharField(choices=[('NONE', 'NONE'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL'), ('BOTH', 'BOTH')], default='NONE', max_length=10)),
                ('nurse_channel', models.CharField(choices=[('NONE', 'NONE'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL'), ('BOTH', 'BOTH')], default='NONE', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='core_emails.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('PATIENT', 'PATIENT'), ('NURSE', 'NURSE')], max_length=10)),
                ('channel', models.CharField(choices=[('NONE', 'NONE'), ('SMS', 'SMS'), ('EMAIL', 'EMAIL'), ('BOTH', 'BOTH')], max_length=10)),
                ('destination', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_events', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='core_emails.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
