# Generated by Django 4.2.27 on 2026-02-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0009_prescriptionnotificationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionnotificationsettings',
            name='free_text_message',
            field=models.TextField(blank=True, default='', help_text='Message libre optionnel ajouté aux notifications (sans données médicales).'),
        ),
    ]
