# Generated by Django 4.2.27 on 2026-03-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0011_prescription_delete_reason_prescription_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRenewalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Ordonnance reçue'), ('IN_PROGRESS', 'En cours de préparation'), ('READY', 'Prête à être délivrée'), ('DELIVERED', 'Délivrée'), ('BLOCKED', 'Bloquée (problème)'), ('ARCHIVED', 'Archivée')], default='RECEIVED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_5_patient_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_5_patient_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3_patient_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_3_patient_sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_cycles', to='core_emails.prescription')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('prescription', 'cycle_number')},
            },
        ),
    ]
