# Generated by Django 4.2.27 on 2026-03-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0012_renewal_cycle_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionnotificationsettings',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='Date du premier démarrage réel du traitement.', null=True),
        ),
    ]
