# Generated by Django 4.2.27 on 2026-06-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_emails', '0014_remove_prescriptionnotificationsettings_processing_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenewalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(default='La Grande Pharmacie de Fives', max_length=255, verbose_name='Nom de la pharmacie')),
                ('phone', models.CharField(blank=True, default='03 20 56 50 05', max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('opening_time', models.TimeField(default='10:00', verbose_name="Heure d'ouverture")),
                ('closing_time', models.TimeField(default='19:00', verbose_name='Heure de fermeture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paramètres renouvellements',
                'verbose_name_plural': 'Paramètres renouvellements',
            },
        ),
        migrations.CreateModel(
            name='RenewalNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du modèle')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=20, verbose_name='Canal')),
                ('subject', models.CharField(blank=True, default='', help_text='Utilisé uniquement pour les emails.', max_length=255, verbose_name='Objet')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Modèle notification renouvellement',
                'verbose_name_plural': 'Modèles notification renouvellement',
                'ordering': ['channel', 'name'],
                'indexes': [models.Index(fields=['channel'], name='core_emails_channel_7ce595_idx'), models.Index(fields=['active'], name='core_emails_active_52c423_idx')],
            },
        ),
        migrations.CreateModel(
            name='RenewalNotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple : J-21, J-10, J-5, J-2', max_length=100, verbose_name='Nom')),
                ('days_before', models.PositiveIntegerField(help_text='Exemple : 21 pour J-21', verbose_name='Nombre de jours avant échéance')),
                ('send_sms', models.BooleanField(default=True, verbose_name='Envoyer SMS')),
                ('send_email', models.BooleanField(default=False, verbose_name='Envoyer Email')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Règle de notification renouvellement',
                'verbose_name_plural': 'Règles de notification renouvellement',
                'ordering': ['sort_order', '-days_before', 'name'],
                'indexes': [models.Index(fields=['active'], name='core_emails_active_33b217_idx'), models.Index(fields=['days_before'], name='core_emails_days_be_34718d_idx'), models.Index(fields=['sort_order'], name='core_emails_sort_or_400ab0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Jour fermé',
                'verbose_name_plural': 'Jours fermés',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='core_emails_date_a2b7ec_idx'), models.Index(fields=['active'], name='core_emails_active_72eaaf_idx')],
            },
        ),
    ]
