# Generated by Django 6.0.6 on 2026-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_emails", "0019_backfill_legacy_renewal_deliveries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Reçue"),
                    ("IN_PROGRESS", "En cours"),
                    ("READY", "Prête"),
                    ("DELIVERED", "Délivrée"),
                    ("REJECTED", "Refusée"),
                    ("BLOCKED", "Bloquée (legacy)"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionrenewalcycle",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Reçue"),
                    ("IN_PROGRESS", "En cours"),
                    ("READY", "Prête"),
                    ("DELIVERED", "Délivrée"),
                    ("REJECTED", "Refusée"),
                    ("BLOCKED", "Bloquée (legacy)"),
                    ("ARCHIVED", "Archivée"),
                ],
                default="RECEIVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Reçue"),
                    ("IN_PROGRESS", "En cours"),
                    ("READY", "Prête"),
                    ("DELIVERED", "Délivrée"),
                    ("REJECTED", "Refusée"),
                    ("BLOCKED", "Bloquée (legacy)"),
                    ("ARCHIVED", "Archivée"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionstatushistory",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("RECEIVED", "Reçue"),
                    ("IN_PROGRESS", "En cours"),
                    ("READY", "Prête"),
                    ("DELIVERED", "Délivrée"),
                    ("REJECTED", "Refusée"),
                    ("BLOCKED", "Bloquée (legacy)"),
                    ("ARCHIVED", "Archivée"),
                ],
                max_length=20,
            ),
        ),
    ]
