# Generated by Django 4.2.27 on 2025-12-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
