# Generated by Django 4.2.27 on 2025-12-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gmail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailmessage',
            name='from_email',
            field=models.EmailField(help_text="Adresse email de l'expéditeur", max_length=254),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='processed_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de traitement par l'application"),
        ),
        migrations.AlterField(
            model_name='gmailmessage',
            name='received_at',
            field=models.DateTimeField(help_text='Date de réception Gmail'),
        ),
    ]
