# Generated by Django 4.2.27 on 2025-12-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='per_page',
            field=models.PositiveSmallIntegerField(choices=[(10, '10 lignes'), (25, '25 lignes'), (50, '50 lignes')], default=10, help_text='Nombre de lignes affichées par page dans les listes'),
        ),
    ]
